version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    container_name: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27017: 27017'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - PORT=${MONGO_USERNAME}
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
